msys2/msys2.github.io

index.html, stylesheets/custom.css
- clean up the HTML a bit
- improve the look
- replace `pacman -Syu` with two commands, so people don't get post-install errors
=> Various changes

index.html
Make sure each screenshot is on its own line. Maybe setting `display: block;` would be a better solution but, in any case, something must be done.
=> Add <br> before images

docs/wiki/Devtopics.md
As commented in https://github.com/msys2/msys2.github.io/commit/4ca4e2ab9a709d117e13c1dfd8d2fd3b6856be2e#r39716628.
=> docs/wiki/Devtopics: fix URL to Git for Windows

README.md
Add shields to the readme for the website, the gitter chat and the GHA workflow.
=> readme: add shields (site, gitter and gha)

docs/docs/what-is-msys2.md, docs/docs/who-is-using-msys2.md, docs/index.md, mkdocs.yml
It's hard to pin down what MSYS2 is exactly. This tries to anyway,
while trying not to go into details too much, since most users
don't know what MSYS or POSIX is.
=> Rewrite the introduction

docs/docs/terminals.md
The profiles now go in `"profiles" -> "list"` and there is a required `"guid"` field.
=> Update windows terminal settings format

docs/index.md
Resolves #84 
Just made a minor typo fix on the MSYS2 page
Chololatey -> Chocolatey
=> Fixed typo on main site

docs/docs/ci.md
small fix to make it work by adding `--noconfirm` to commands which seemed to be missing.
=> docs: fix appveyor ci help

docs/dev/mirrors.md
add new mirrors and note about mirrorlist.md
=> mirrors.md

docs/news.md
See https://github.com/msys2/MINGW-packages/pull/7859
=> news: add something about the upcoming ASLR change

web/docs/environments.md
I had to link it twice today in discord and the embeds looks ugly without this :)
=> Add metadata to environments.md

web/wiki/Creating-Packages.md
Since MINGW_INSTALLS is now deprecated, updated usage in the docs to MINGW_ARCH
=> Update MINGW_INSTALLS to MINGW_ARCH

web/dev/mirrors.md
Details in msys2/msys2-packages#2573
=> Add Internet Association of Australia mirror

web/docs/environments.md
Will also need  `web/docs/lang32.png`, not sure where those come from...
=> Add CLANG32 environment

web/docs/environments.md
as used with `pacman`, because I've found myself to check the repos for this information the third time...
=> environments table: add package-prefix

web/docs/who-is-using-msys2.md
Add RubyInstaller2 case in **who-is-using-msys2**.
=> Add RubyInstaller2

web/docs/faq.md
This adds more information about magic number mismatch scenarios.
=> docs: Add documentation about magic number mismatch

web/docs/environments.md
This instance was forgotten in 0ecd2cf
=> Regression from change to ucrt64 as default

web/docs/environments.md
I believe what is referenced is the environment, ie singular -> is.
=> Grammar: are -> is

LICENSE, LICENSE.README.md, web/donate/README.txt, web/sponsors/README.txt
That doesn't fix it for any of the old content, but it's a start.
Fixes #243
=> Add a license for the website content

LICENSE.md, licenses/BSD-3-Clause.txt, licenses/CC-BY-SA-4.0.txt, licenses/CC0-1.0.txt
It was pointed out that BSD might not be a good fit for documentation.
=> Switch to documentation oriented licenses instead

web/docs/ides-editors.md
A copy'n'paste to collect information into one place.
=> Update ides-editors.md to include Visual Studio Code

mkdocs.yml, web/docs/pkgconfig.md
This focuses on things that are special/different compared to Linux.
=> Add a page about pkg-config

web/index.md
Someone copied the whole thing https://discord.com/channels/792780131906617355/1090268024390557787/1090278351601672283
Hope this will make things clear 🙏
=> index: Separate gcc installation command and its output

web/docs/python.md, web/news.md
and adjust the Python docs as well
=> NEWS: add something for the add_dll_directory() change

web/wiki/MSYS2-installation.md
Replace \<base-devel\> with \`base-devel\`
=> Fix typo in MSYS2-installation.md

web/docs/environments.md
=> environments: Clarify supported Windows OSes for UCRT

web/dev/mirrors.md, web/news.md
Related to https://github.com/msys2/msys2-main-server/pull/35
=> NEWS: advertise that rsync now supports TLS

web/docs/who-is-using-msys2.md
=> Update who-is-using-msys2.md: add NUT for Windows

mkdocs.yml, web/docs/c.md
We want to change the default, so add some docs we can point to in the upcoming NEWS entry.
=> Add a page about mingw-w64 wildcard expansion

web/docs/c.md, web/news.md
=> NEWS: add entry about disabling wildcard support by default

web/news.md
See https://github.com/msys2/MSYS2-packages/pull/5448
=> NEWS: Replacing `x86_64-pc-msys` with `x86_64-pc-cygwin`
