- docs/index.md
cygwin is thinking about dropping it next year, so we'll have to do too:
https://cygwin.com/pipermail/cygwin/2020-April/244367.html
Let's start by removing the download button and see if anyone complains :)
> index: Drop references to the 32 bit installer

- docs/index.md
- docs/wiki/History.md
Regarding the second of those two fixes, currently, what's meant to be the first bullet list on https://www.msys2.org/wiki/History/ (beginning right after "The important pieces are:") is not properly rendered. Adding a blank line before the first bulleted point should fix that.
> Fix wiki link location and a bullet list in "History" wiki page

- docs/wiki/Porting.md
NB: The pointer to https://github.com/Alexpux/path_convert might be outdated, since `MSYS2_ARG_CONV_EXCL` is dealt with rather here: https://github.com/msys2/msys2-runtime/blame/2b2cff60c60f5196d77703da892a201bd2d099c9/winsup/cygwin/spawn.cc#L287.   This could be amended, too, but this is far beyond me.
> Filesystem nmspaces: add guidance as to how to prevent path transformation

- .github/workflows/main.yml
Currently, forks cannot test feature branches easily, because CI ignores them. This PR changes the workflow for building all branches except `master`. In this repo, `source` is published only. In forks, any feature branch is published.
> ci: use 'branches-ignore' instead  of 'branches'

- docs/docs/package-management.md
- docs/wiki/Creating-Packages.md
- docs/wiki/MSYS2-reinstallation.md
As pacman generates `.tar.zst` packages now, the documentation is somewhat out of date. I've replaced `.xz` with `.zst` in all corresponding places.
I've extended the documentation in `docs/docs/package-management.md` with `.tar.zst` rather than replacing it, as https://repo.msys2.org contains `.tar.xz` and `.tar.zst` files.
> Replaced .xz with .zst

- web/docs/ci.md
This affects the new Windows runners from gitlab-ci.
> ci: mention the taskkill trick in case CI needs all processes to stop

- web/wiki/Porting.md
The original URL (`https://gnunet.org/sorting-out-stat-thing`) appears to no longer be available, and I was unable to find a new URL on that domain, but did locate an archived copy.
> Fix broken link on Porting.md

- web/index.md
It's not clear if any donations going there would end up somewhere useful,
so better remove them.
We're happy to revert this if that isn't the case though.
> Remove Ray's donation link

- web/docs/who-is-using-msys2.md
In the first commit, existing references are ordered alphabetically.
In the second commit, references to several projects using MSYS2 (setup-msys2) in their CI are added.
> Update 'Who is using MSYS2?'

- web/docs/package-management.md
- web/docs/package-naming.md
follow-up to 97544b5cb7dcd067f5a1f698e44c08dc08e49c72
* title and summary and use of level 2 headers
* copied env name notes from 454f891ade4d5311d91da505377fec9c3c064d55
* a bit of cross-referencing
> packing-naming extended

- web/news.md
As discussed [here](https://www.msys2.org/docs/windows_support/), around the end of this year, MSYS2 will stop supporting Windows <8.1. Let's amplify the messaging on the news page of the MSYS2 project.
> News: announce the upcoming end of Windows 7/8 support

- web/wiki/Setting-up-SSHd.md
The link refers to a page that no longer has instructions, so I added some instructions to the page itself. The methodology is basically the same as [were on](https://github.com/Diablo-D3/dotfiles/blob/87c8fc8e397c072914e48d5394b46a60262e541b/modules/os-win/sshd_msys2.bat) the linked page.
edit: although trying to use scp with this shell in use instead of cmd results in this error, so there may be some improvements possible:
```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```
> Win32-OpenSSH instructions: replaced dead link with instructions

- web/docs/terminals.md
Convert deprecated fontFace and fontSize terminal config options to use the font object
> fontFace and fontSize are deprecated terminal config options

- web/wiki/MSYS2-installation.md
32 bit msys2 installation is no longer supported. It was dropped in 17/05/2022 https://www.msys2.org/news/#2020-05-17-32-bit-msys2-no-longer-actively-supported
Fixes https://github.com/msys2/msys2.github.io/issues/252
> wiki: Remove reference to 32 bit msys2 installation

- web/docs/ci.md
Many thanks for MSYS2!
I have started to use MSYS2 for GitLab CI/CD, beginning with `libntlm` but will add it to many other projects too.
See example job output: https://gitlab.com/gsasl/libntlm/-/jobs/5840322953
Thanks,
Simon
> CI: add a GitLab example

- web/index.md
Removed the extra ".exe" of the installer filename, which was first introduced in [this commit](https://github.com/msys2/msys2.github.io/commit/5b0bfd8d030d5acefc93ce886e0721d85a33d4a7). >_<
> fix: correct typo in installer filename

- mkdocs.yml
This PR updates the `mkdocs.yml` file to add and alphabetically sort common language translation options. The following languages have been added:
- German (Deutsch)
- Spanish (Español)
- French (Français)
- Japanese (日本语)
- Korean (한국어)
- Chinese (中文)
Please review and merge. Thank you!
> Add and sort common language translation options

- web/docs/ides-editors.md
I should have done this earlier. now it became harder to change MSYS2 section in Zed docs, so this will be easier to maintain
edit: I edited file in GitHub, that's why branch has that silly name
> IDEs and editors: add Zed

- web/docs/ides-editors.md
Zed 0.177.x added Git panel for all users. 98% of use cases are satisfied with it. so remove that workaround to less confuse users
_better to merge after Zed package update is available in the repo_
> ides-editors: remove `EDITOR` env workaround for Zed

- web/docs/git.md
Git for Windows' wiki pages were migrated in https://github.com/git-for-windows/git-for-windows.github.io/pull/59.
> Replace outdated links to Git for Windows' wiki

- web/docs/package-naming.md
The documentation suggested that the environment variable `MINGW_PACKAGE_PREFIX` contains a trailing `-`, but that is not actually the case. Correct that.
> package-naming.md: Fix package name prefix

- web/docs/faq.md
Related to https://github.com/msys2/MSYS2-packages/issues/5476.
This PR changes the title of the second FAQ entry, which will make any old relative links to the second entry invalid (they will link to the top of the FAQ page instead of the relevant entry). I do not have much experience with using mkdocs (but I plan to fix that soon), but I assume that it supports the GitHub Markdown extension which allows to override title anchors. This could be used to keep the old anchor. A brief search through MSYS2's docs did not show me any links to the second FAQ entry (I might have missed some), external websites/resources may still link to the old anchor though.
> FAQ: mention antivirus intercepting TLS

- web/docs/faq.md
This PR is a small addendum to https://github.com/msys2/msys2.github.io/pull/390.
I would have included a link that explains how to turn this off in Norton, but I personally do not use it, so I would not be able to verify it and I have not been able to find any official Norton docs discussing this matter (in contrast to Avast, which has an official blogpost about this which I've linked).
Related to https://github.com/msys2/MSYS2-packages/issues/5476
> FAQ: mention Norton intercepting TLS

- web/codeofconduct.md
With many drive by GitHub users it's not really feasible/possible to contact them privately.
> CoC: add an extension to allow public warnings
